### ISSUE TITLE
Should this repo be translated to GERMAN?

### ISSUE THREAD

**Issue by eddex** [eddex/awesome-hslu#20]
Da die meisten Module in deutscher Sprache gehalten werden und viele der Zusammenfassungen ebenfalls in Deutsch verfasst sind, macht es eventuell Sinn, dieses Repository ebenfalls auf Deutsch zu übersetzen.

Bitte mit einem 👍 oder 👎 eure Meinung angeben oder einen Kommentar schreiben.

**Comment by KilnOfTheSecondFlame** [comment]
As we are on an international site, and because the advanced modules are mostly in english, I'd say leave it english.

**Comment by eddex** [comment]
thanks for voting, I consider this closed.
