### ISSUE TITLE
add repos of @daveschafer

### ISSUE THREAD

**Issue by eddex** [eddex/awesome-hslu#7]
@daveschafer

**Comment by daveschafer** [comment]
These Repos should be good to go (regarding completeness, documentation )

CSA- Project HS17
https://github.com/daveschafer/CSA

SWE - Project FS18
https://github.com/daveschafer/SWE-Project-FS18

IOT - Project HS18
https://github.com/daveschafer/IOT-HS18

**Comment by eddex** [comment]
Feel free to create a pull request. Otherwise I'll add them as soon as I find the time.
